Entire Project CR
EllaMenachemi/Password-Manager pull request #2
Opened 2024-08-24 11:30 UTC by EllaMenachemi

2024-08-27 07:59 UTC, captainxor commented
Please change the naming of the files to reflect their actual roles in the project

2024-08-27 08:00 UTC, captainxor commented
Also, I'd recommend that you have small instructions in your `README.md` file explaining how to run the different components in your server

2024-08-27 09:00 UTC, captainxor requested changes
Let's start with these comments :)

2024-08-27 09:00 UTC, captainxor commented on client_manager.py
> +    logic_client = Client()
Not too important but all of your code does support configuration but doesn't ever pass it. If you want, you could use different libraries for argument parsing (fire, click, argparse, whatever you choose)

2024-08-27 09:00 UTC, captainxor commented on client_manager.py
> +    window.geometry("500x500")
Usually, it's not preferable to use constants like that in code, it would be nice to have something like `WINDOW_SIZE="500x500"`

2024-08-27 09:00 UTC, captainxor commented on client_manager.py
> +    password_manager_client = Client()
This isn't used anywhere, you can delete

2024-08-27 09:00 UTC, captainxor commented on client_manager.py
> +#class Manager:
Delete unused / commented code

2024-08-27 09:00 UTC, captainxor commented on client_gui_password_manager.py
> +    def __init__(self, master, client, username = ""):
Kind of an issue here, you pass on a client object, but you initialize a new one instead and don't use the passed parameter, please decide how you want to operate

2024-08-27 09:00 UTC, captainxor commented on client_gui_password_manager.py
> +    def create_window(self):
Unused code, delete

2024-08-27 09:00 UTC, captainxor commented on client_gui_password_manager.py
> +        master = self.master
Preferable to use the self.master instead of a local variable here so you won't be confused as to what object is in use

2024-08-27 09:00 UTC, captainxor commented on client_gui_password_manager.py
> +        master = self.master
Same not about not using local variables when not needed

2024-08-27 09:00 UTC, captainxor commented on client_gui_password_manager.py
> +    def sign_up1(self):
sign_up1 is a bad name, please find a more meaningful name

2024-08-27 09:00 UTC, captainxor commented on client_gui_password_manager.py
> +        sign_up = tkinter.Label(master, text="Sign Up", font=("italic", 16))
I'll write this once, but it's relevant for this entire file, it would be better to use constants in a convention like CONSTANT_VARIABLE_NAME="value"

2024-08-27 09:00 UTC, captainxor commented on client_gui_password_manager.py
> +                                             command=lambda button_pressed="check username validity Clicked":
instead of having the button_pressed string as a variable, pass the constant itself, what you did is somewhat cofusing

2024-08-27 09:00 UTC, captainxor commented on client_gui_password_manager.py
> +    def check_button_pressed(self, button_pressed, data1, data2):
Change data1 and data2 to more meaningful names

2024-08-27 09:00 UTC, captainxor commented on client_gui_password_manager.py
> +        print("get data: " + get_data)
A nice recommendation I have for you, python has logging capabilities so instead of print, you could use logging.info or something else. I'll explain it f2f but you can look at the python logging library if you want

2024-08-27 09:00 UTC, captainxor commented on client_gui_password_manager.py
> +    def check_button_pressed(self, button_pressed, data1, data2):
Also, button_pressed is also a very confusing name, find another name to fit it better

2024-08-27 09:00 UTC, captainxor commented on client_gui_password_manager.py
> +        if button_pressed == "check username validity Clicked":
button_pressed should be an enum, read about enums and use them instead of a string

2024-08-27 09:00 UTC, captainxor commented on client_gui_password_manager.py
> +    def sign_up_page2(self):
Bad name, find something more meaningful

2024-08-27 09:00 UTC, captainxor commented on client2_password_manager.py
> +        self.my_socket.connect(('127.0.0.1', 8820))
although you pass argument to init Client, you don't use them (i.e self.host and self.port), make sure it use them instead

2024-08-27 09:00 UTC, captainxor commented on client2_password_manager.py
> +        z_fill_length = length.zfill(2)
Please write an assumption that message length is less than 100 bytes

2024-08-27 09:00 UTC, captainxor commented on client2_password_manager.py
> +        z_fill_length = length.zfill(2)
I can explain it f2f, but usually, it is recommended to pass sizes in a binary manner, not their string representation. There's a python builtin library called struct for that

2024-08-27 09:00 UTC, captainxor commented on client2_password_manager.py
> +        username_final = " ".join(words)
Why do it like that? You could do just concatenate, use f-strings or do all other sorts of stuff. This is somewhat confusing as to what happens here

2024-08-27 09:00 UTC, captainxor commented on client2_password_manager.py
> +        final_message = " ".join(description_and_data)
Again, why use join for this?

2024-08-27 09:00 UTC, captainxor commented on client2_password_manager.py
> +        j = 0
why does j start from 0 if the string contains "username log in:" at the start?

2024-08-27 09:00 UTC, captainxor commented on client2_password_manager.py
> +        self.username_to_app = username_and_password[17:j]
What does the number 17 mean? if it's a length of something, it would be tidier to use len(variable) instead

2024-08-27 09:00 UTC, captainxor commented on client2_password_manager.py
> +        if site_name[0:4] == "http":
use site_name.startswith("http") instead, it is more readable

2024-08-27 09:00 UTC, captainxor commented on client2_password_manager.py
> +                    sys.exit(0)
You just exit here, give a message as to why you exited (log or print or something)

2024-08-27 09:00 UTC, captainxor commented on client2_password_manager.py
> +            site_name = extracted_info.domain
site_name isn't used

2024-08-27 09:00 UTC, captainxor commented on client2_password_manager.py
> +                html = urlopen(url)
html isn't used

2024-08-27 09:00 UTC, captainxor commented on client2_password_manager.py
> +            except HTTPError as e:
you could do something like except (HTTPError, URLError) as e: so it would be tidier

2024-08-27 09:00 UTC, captainxor commented on password_manager_server_updated.py
> +        self.server_socket.bind(('0.0.0.0', 8820))
Use self.host and self.port instead

2024-08-27 09:00 UTC, captainxor commented on password_manager_server_updated.py
> +            if data[:17] == "username sign up:":
don't use constant numbers for this, also, you can use data.startswith

2024-08-27 09:00 UTC, captainxor commented on password_manager_server_updated.py
> +    def check_client_message(self, data, open_client_sockets):
open_client_sockets isn't used

2024-08-27 09:00 UTC, captainxor commented on password_manager_server_updated.py
> +            return reply
if the message isn't any of the messages you sent, reply would return as None which is problematic

2024-08-27 09:00 UTC, captainxor commented on password_manager_server_updated.py
> +        site_name = data[11:j]
number constants are bad :)

2024-08-27 09:00 UTC, captainxor commented on password_manager_server_updated.py
> +            if data[j] == "(":
what does "(" mean in your case here?

2024-08-27 09:00 UTC, captainxor commented on password_manager_server_updated.py
> +        extracted_info = tldextract.extract(url)
isn't used anywhere

2024-08-27 09:00 UTC, captainxor commented on password_manager_server_updated.py
> +        file_path = "C:\\Users\\Ella Menachemi\\OneDrive\\Desktop\\password_manager\\" + username_to_app + "\\" + site
Please use a configurable path instead

2024-08-27 09:00 UTC, captainxor commented on password_manager_server_updated.py
> +        file_path = "C:\\Users\\Ella Menachemi\\OneDrive\\Desktop\\password_manager\\" + username_to_app + "\\" + site
Also, there's a better way to specify paths in python, use r"C:\Users\" whatever instead of doing \\ everywhere

2024-08-27 09:00 UTC, captainxor commented on password_manager_server_updated.py
> +        file_path = "C:\\Users\\Ella Menachemi\\OneDrive\\Desktop\\password_manager\\" + username_to_app + "\\" + site
If you want an even better alternative, there are libraries called os.path and pathlib, they are very useful :)

2024-08-27 09:00 UTC, captainxor commented on password_manager_server_updated.py
> +            file = open(path, "r")
You've already got the file handle, no need to do open it again

2024-08-27 09:00 UTC, captainxor commented on password_manager_server_updated.py
> +            file = open(path, "r")
Also, you can use file.read_text or something similar to read the file

2024-08-27 15:59 UTC, captainxor commented on password_manager_server_updated.py
> +    def __init__(self, host='0.0.0.0', port=8820, username_to_app = "", current_socket = socket.socket()):
Why is current_socket initialized here? init it only when needed

2024-08-27 16:00 UTC, captainxor commented on password_manager_server_updated.py
> +        file_path = "C:\\Users\\Ella Menachemi\\OneDrive\\Desktop\\password_manager\\" + data
Make the root directory of the files for the server configurable, and save as a member of the class

2024-08-27 16:01 UTC, captainxor commented on password_manager_server_updated.py
> +        file_path = "C:\\Users\\Ella Menachemi\\OneDrive\\Desktop\\password_manager\\" + data
Also use pathlib functionality (/ as a divider for folders) to make the code more clean

2024-08-27 16:03 UTC, captainxor commented on password_manager_server_updated.py
> +        while j != len(data):
use data.index(), or data.find() or data.search(), whatever you see fit :)

2024-08-27 16:03 UTC, captainxor commented on password_manager_server_updated.py
> +        if site_name[0:4] == "http":
site_name.startwith() :)

2024-09-07 10:37 UTC, EllaMenachemi commented on client_gui_password_manager.py
> +        sign_up = tkinter.Label(master, text="Sign Up", font=("italic", 16))
should i create a constant variable even when there are different sizes? for example when "x=30" and for another button it is "x=50"? should i create a constant variable for each label/button then?

2024-09-08 10:26 UTC, merged